export const SignInMessage = "Signing in...";
export const SignUpMessage = "Creating a new account...";
export const AddCarMessage = "Adding a new car...";
export const AddManufactureMessage = "Adding a new manufacture...";
export const AddCarType = "Adding a new car type...";
export const EmailConfirmationMessage = "Confirming your email...";
export const DefaultErrorMessage = "Oops, something goes wrong.\nPlease, try again";
export const EnterCredentialsMessage = "Please, re-enter your credentials";
export const InvalidInput = "Please, check your input data and try again";
